### PR TITLE
fixed string format

### PR DESCRIPTION
**Pull request by kootenpv**

### CODE REVIEW

**Comment by kootenpv** [comment]
I signed it!

**Comment by kootenpv** [comment]
These should have been 2 separate pull requests, but that failed. 

I hope you'd be happy to support python 3 as well :)!

**Comment by amahabal** [comment]
Hi kootenpv,

Thanks for the pull request. However, there may be some issues here. When I removed the *-shelf files and tried to initialize with python3, I ran into the following issue:

========

Traceback (most recent call last):
  File "initialize.py", line 22, in <module>
    util.CreateShelves(True)
  File "/usr/local/google/RELEASE/categorybuilder_public/category_builder_util.py", line 88, in CreateShelves
    CreateShelf(GetPath(I_TO_F_INPUT), GetPath(I_TO_F_SHELF), linecount=200000, verbose=verbose)
  File "/usr/local/google/RELEASE/categorybuilder_public/category_builder_util.py", line 73, in CreateShelf
    for line in csvreader:
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

==========

**Comment by amahabal** [comment]
Hi @kootenpv, 

I have now fixed the Python3 issue. Multiple tiny changes were needed (including the bytes-vs-strings business).

Best,
  Abhijit

**Pull request closed without merging**
